"""your message here

Revision ID: 34a8f19d1766
Revises: 6a1eb01bd469
Create Date: 2025-07-15 22:48:03.827997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a8f19d1766'
down_revision: Union[str, Sequence[str], None] = '6a1eb01bd469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_intent_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billingcycle'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), nullable=True),
    sa.Column('meta_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.add_column('subscription_plans', sa.Column('monthly_price', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('yearly_price', sa.Integer(), nullable=True))
    op.drop_column('subscription_plans', 'stripe_yearly_price_id')
    op.drop_column('subscription_plans', 'price')
    op.drop_column('subscription_plans', 'stripe_monthly_price_id')
    op.add_column('user_subscriptions', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('last_payment_intent_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('payment_method_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('next_renewal_date', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('renewal_attempts', sa.Integer(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('renewal_failed', sa.Boolean(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('default_payment_method_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auto_renew_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'auto_renew_enabled')
    op.drop_column('users', 'default_payment_method_id')
    op.drop_column('user_subscriptions', 'failure_reason')
    op.drop_column('user_subscriptions', 'renewal_failed')
    op.drop_column('user_subscriptions', 'last_renewal_attempt')
    op.drop_column('user_subscriptions', 'renewal_attempts')
    op.drop_column('user_subscriptions', 'next_renewal_date')
    op.drop_column('user_subscriptions', 'payment_method_id')
    op.drop_column('user_subscriptions', 'last_payment_intent_id')
    op.drop_column('user_subscriptions', 'last_payment_date')
    op.add_column('subscription_plans', sa.Column('stripe_monthly_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('stripe_yearly_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscription_plans', 'yearly_price')
    op.drop_column('subscription_plans', 'monthly_price')
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_table('payment_history')
    # ### end Alembic commands ###
