"""Add Stripe price IDs to subscription plans

Revision ID: 6a1eb01bd469
Revises: 71d818277209
Create Date: 2025-07-11 00:37:57.172668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1eb01bd469'
down_revision: Union[str, Sequence[str], None] = '71d818277209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('stripe_monthly_price_id', sa.String(), nullable=True))
    op.add_column('subscription_plans', sa.Column('stripe_yearly_price_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'stripe_yearly_price_id')
    op.drop_column('subscription_plans', 'stripe_monthly_price_id')
    # ### end Alembic commands ###
