"""Added last_login column

Revision ID: 71d818277209
Revises: 
Create Date: 2025-07-07 21:23:31.347157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d818277209'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('queries_used', sa.Integer(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('documents_uploaded', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('user_subscriptions', 'documents_uploaded')
    op.drop_column('user_subscriptions', 'queries_used')
    # ### end Alembic commands ###
